### ISSUE TITLE
Reintrodução do padrão antigo de estilização

### ISSUE THREAD

**Issue by condini-mastheus** [Rocketseat/rocketseat-vscode-react-native-snippets#4]
Olá,
Estou no meio de um projeto no momento e não pretendo introduzir styled components nesse momento, logo, snippet era muito útil, seria possível coloca-lo novamente?
Snippet em questão:
`style`
```
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
 }
});
```

**Comment by diego3g** [comment]
@condini-mastheus As extensões para VSCode são sempre atualizadas para contemplar as features explicadas no bootcamp. Mas uma dica pra você é que você pode criar um snippet em seu próprio VSCode.

1. Clique CTRL + SHIFT + P
2. Configure User Snippets
3. New Global Snippet File
4. Salve com o nome que preferir o arquivo
5. Dentro deixe o conteúdo do arquivo assim:

```json
{
  "styles": {
    "prefix": "styles-rn",
    "body": [
      "import { StyleSheet } from 'react-native';",
      "",
      "const styles = StyleSheet.create({",
      "  ${1}",
      "});",
      "",
      "export default styles;",
      ""
    ],
    "description": "Create react-native Style file"
  },
}
```

**Comment by condini-mastheus** [comment]
Obrigado @diego3g!
Vou adaptar essa solução dentro do meu vscode.
